[package]
name = "penguins_party"
version = "0.1.0"
authors = ["TheHellBox <thehellbox11@gmail.com>"]
edition = "2018"

[dependencies]
glium = "0.25"
specs = "0.14.3"
specs-derive = "0.4"
rodio = "0.9"
png =   "0.14"
nalgebra = "0.18"
ncollide2d = "0.19"
