[package]
name = "level_editor"
version = "0.1.0"
authors = ["TheHellBox <thehellbox11@gmail.com>"]
edition = "2018"

[dependencies]
glium = "0.25"
specs = "0.14.3"
specs-derive = "0.4"
png = "0.14"
nalgebra = "0.18"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
